import HomePass from '#models/home_pass'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class HomepassSeeder extends BaseSeeder {
  async run() {
    await HomePass.createMany([
      {
        homepassId: '20125H124.3.02103',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6113629, 98.6177764',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CC',
        no: '1',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1031-M136S1',
        spliterDistribusiKoordinat: '3.61135, 98.61805',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02104',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6112934, 98.6178524',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CC',
        no: '11',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1031-M136S1',
        spliterDistribusiKoordinat: '3.61135, 98.61805',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02105',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6112934, 98.6178711',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CC',
        no: '11A',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1031-M136S1',
        spliterDistribusiKoordinat: '3.61135, 98.61805',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02106',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6113567, 98.6177734',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CC',
        no: '3',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1031-M136S1',
        spliterDistribusiKoordinat: '3.61135, 98.61805',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02107',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6113233, 98.6178228',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CC',
        no: '5',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1031-M136S1',
        spliterDistribusiKoordinat: '3.61135, 98.61805',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02108',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.5524863, 98.6001287',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CC',
        no: '7',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1031-M136S1',
        spliterDistribusiKoordinat: '3.61135, 98.61805',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02109',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6114023, 98.6179519',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CC',
        no: '9',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1031-M136S1',
        spliterDistribusiKoordinat: '3.61135, 98.61805',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02110',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6112634, 98.6175352',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '1',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1033-M136S3',
        spliterDistribusiKoordinat: '3.61103, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02111',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110831, 98.6179635',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '10',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1032-M136S2',
        spliterDistribusiKoordinat: '3.61112, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02112',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110927, 98.6179779',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '11',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1033-M136S3',
        spliterDistribusiKoordinat: '3.61103, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02113',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110927, 98.6179742',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '11A',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1033-M136S3',
        spliterDistribusiKoordinat: '3.61103, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02114',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110099, 98.6180523',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '12',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1032-M136S2',
        spliterDistribusiKoordinat: '3.61112, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02115',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110099, 98.6180136',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '12 A',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1032-M136S2',
        spliterDistribusiKoordinat: '3.61112, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02116',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110453, 98.618062',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '2',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1032-M136S2',
        spliterDistribusiKoordinat: '3.61112, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02117',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.611078, 98.6179013',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '2A',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1032-M136S2',
        spliterDistribusiKoordinat: '3.61112, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02118',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110785, 98.6178736',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '3',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1033-M136S3',
        spliterDistribusiKoordinat: '3.61103, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02119',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110755, 98.6179198',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '5',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1033-M136S3',
        spliterDistribusiKoordinat: '3.61103, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02120',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6111334, 98.6177225',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '6',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1032-M136S2',
        spliterDistribusiKoordinat: '3.61112, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02121',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110766, 98.6179506',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '7',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1033-M136S3',
        spliterDistribusiKoordinat: '3.61103, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
      {
        homepassId: '20125H124.3.02122',
        projectId: 'P2402325',
        projectName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        region: 'West',
        subRegion: 'Northern Sumatera',
        areaName: 'FBECRD MDN PERUM.GIVENCY ONE TH 04',
        province: 'Sumatera Utara',
        city: 'Kota Medan',
        district: 'Medan Helvetia',
        subDistrict: 'Tanjung Gusta',
        postalCode: 20125,
        homepassedCoordinate: '3.6110801, 98.6179333',
        homepassType: 'H1',
        residentType: 'Perumahan',
        residentName: 'Rumah PERUM.GIVENCY ONE TH 04',
        streetName: 'Jl. Komplek Perumahan Givency One Blok CD',
        no: '8',
        unit: null,
        popId: 'MDN-13',
        splitterId: 'MDN-13-D1032-M136S2',
        spliterDistribusiKoordinat: '3.61112, 98.61804',
        rfsDate: new Date('2024-12-19'),
      },
    ])
  }
}
