services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coverage_be
    ports:
      - '${PORT:-3333}:3333'
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
    networks:
      - coverage_network

  postgres:
    image: postgis/postgis:17-3.5-alpine
    container_name: postgres_postgis
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-fiberstar}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - /home/fajar/postgresql/data:/var/lib/postgresql/data
    networks:
      - coverage_network

volumes:
  postgres_data:

networks:
  coverage_network:
